openapi: 3.0.1
info:
  title: API de Usuarios
  description: API para manejar usuarios en el sistema.
  version: 1.0.0
servers:
  - url: "http://localhost:8080/api"
    description: Servidor de desarrollo

paths:
  /api/users:
    get:
      summary: Obtener todos los usuarios
      tags:
        - Users
      responses:
        "200":
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          description: Error interno del servidor

    delete:
      summary: Eliminar cuentas de usuarios inactivas
      tags:
        - Users
      responses:
        "200":
          description: Usuarios inactivos eliminados con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Error interno del servidor

  /api/users/{id}:
    delete:
      summary: Eliminar un usuario específico
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del usuario a eliminar
      responses:
        "200":
          description: Usuario eliminado con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Error interno del servidor

components:
  schemas:
    User:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [admin, usuario]
        lastConnection:
          type: string
          format: date-time
